#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Feb 01 05:35:15 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=BSL_v10.1.zip
enableShaders=true
