#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jan 23 06:58:02 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=BSL_v10.1.zip
enableShaders=true
